spring:
  application:
    name: spring-boot-jpa-project
  
  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 콘솔 설정 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.umcseoul: DEBUG

# 서버 설정
server:
  port: 8080
